### ISSUE TITLE
Support for pretty printing data to the terminal?

### ISSUE THREAD

**Issue by evelant** [adzejs/adze#142]
Does adze support pretty printing JSON objects/arrays to the terminal? That could be really useful especially if JSON objects could be color highlighted.

**Comment by AJStacy** [comment]
Hi @evelant,

Are you requesting this feature when in "machineReadable" mode or just when generating a standard formatted log? Are you referring to the node terminal or the browser console?

**Comment by evelant** [comment]
Referring to node (I use react-native so the environment is similar to node). In development it would be useful to pretty format and highlight JSON log output. Right now I'm using a simple custom log wrapper that does a JSON.stringify and then piping my output in the shell to a formatting utility such as https://github.com/brocode/fblog (or pino-pretty etc). That works OK but unless I want to fork the external log formatters it's a bit rigid. 

https://github.com/xpl/ololog is a nice approach for dev log tooling but unfortunately it's written in a really inscrutable style of plain JS that's almost downright hostile to Typescript and makes it really hard to extend/modify.

I was curious if adze had an approach for pretty-printing logs in dev (or perhaps even later when consuming JSON output from production). I haven't been able to find a really great solution to this bit of dev tooling yet.

**Comment by AJStacy** [comment]
I think this would be a great feature for Adze to adopt as a log modifier. I'll label this as a feature request and hopefully include it in version 2 which will be coming soon.

**Comment by AJStacy** [comment]
Adze v2 now supports better formatting options!
