### ISSUE TITLE
Require cycles reported on Expo

### ISSUE THREAD

**Issue by tiagobnobrega** [adzejs/adze#175]
Hi. I'm using it on expo and it's reporting a few require cycles:

```
 ../../node_modules/adze/functions/index.js -> ../../node_modules/adze/functions/data.js -> ../../node_modules/adze/functions/global.js -> ../../node_modules/adze/adze-global.js -> ../../node_modules/adze/tools.js -> ../../node_modules/adze/functions/index.js
 ```
 
 ```
 ../../node_modules/adze/constants.js -> ../../node_modules/adze/formatters/common/index.js -> ../../node_modules/adze/formatters/common/common.js -> ../../node_modules/adze/formatters/formatter.js -> ../../node_modules/adze/functions/index.js -> ../../node_modules/adze/functions/data.js -> ../../node_modules/adze/functions/type-guards.js -> ../../node_modules/adze/constants.js
 ```

**Comment by AJStacy** [comment]
I'm not familiar with Expo. Is this the framework you are referring to?
https://expo.dev/

Also, when you say "require cycles" are you meaning that there are some imports as commonjs requires?

**Comment by tiagobnobrega** [comment]
Hi. Yes it's the [expo.dev](https://expo.dev/). It's just warnings and it's referring to circular dependencies.
It's for react-native development. I would investigate further, but I have to move away from this library right now. 

I really liked it, but I'm also facing some other issues related to not running on a node environment: 

1 - `Cannot resolve node:process` when running on android Hermes.
2- `Cannot read properties of undefined (reading 'indexOf')` from `chalk/source/vendor/supports-color/index.js` when running on the browser.
Maybe it's related to the chalk dependency as it heavily assumes it's running on a node/deno environment. Something like [https://github.com/alexeyraspopov/picocolors](picocolors) could be useful.

Anyway. I would love to contribute more, and I might give it another shot in the near future. I just need to keep moving with this project. Sorry for wasting your time

**Comment by AJStacy** [comment]
@tiagobnobrega , Those are probably all related to working within a mobile app framework. Adze is likely not properly detecting your environments which is why it's trying to use Chalk in the browser (it shouldn't do that). Part of its environment detection is based around detecting whether "Window" or "global" are present.

I completely understand if you need to move on to something else, however, fixing these issues should be trivial if I'm able to test adze in these environments.

I will leave this ticket open so that I can add support for Expo.

Thank you!

**Comment by vanjaoljaca** [comment]
> 1 - Cannot resolve node:process when running on android Hermes.

FWIW the first problem can be fixed with:

metro.config.js:
```
var extraNodeModules = {
  "#ansi-styles": path.resolve(__dirname, 'node_modules/ansi-styles'),
  "#supports-color": path.resolve(__dirname, 'node_modules/supports-color'),
  'node:process': require.resolve('process/browser'),
  'node:os': require.resolve('os-browserify/browser'),
  'node:tty': require.resolve('tty-browserify'),
};

const config = getDefaultConfig(__dirname);

config.transformer.getTransformOptions = async () => ({
  transform: {
    experimentalImportSupport: false,
    inlineRequires: true,
  },
});

config.resolver.extraNodeModules = extraNodeModules;
```
(also yarn/npm add those modules)

this might be a path that helps with chalk v5 support

**Comment by AJStacy** [comment]
@vanjaoljaca we seem to be attempting to resolve issues for this environment also in https://github.com/adzejs/adze/issues/180 . Do you believe the better solution is to prescribe the packages you've listed above or to recommend the Chalk downgrade?

**Comment by vanjaoljaca** [comment]
yes I saw too late that this is a duplicate. there are two pathways to solving this, and neither is working for me at the moment. I think the ideal solution would be to not have to hack in changes to the bundler w/ polyfill, which is what we're discussing in the other report

**Comment by AJStacy** [comment]
@tiagobnobrega , can we close this issue now or are you still seeing the require cycles?

**Comment by AJStacy** [comment]
@tiagobnobrega , I'm going to go ahead and close this issue. If it's still a problem, let me know and I will reopen it.
